config/routes.rb
Rails.application.routes.draw do

    #管理者側ルーティング
      devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
     namespace :admin do
  get '/' => 'homes#top' 
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update] 
  resources :orders, only: [:show, :update,] do
    member do
      patch :update_status
    end
  end
  resources :order_details, only: [:update]
end

  
  
    #顧客側ルーティング
      devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
   
    scope module: :public do
    root :to =>"homes#top" 
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check_out'
        get 'withdraw'
        patch 'withdraw_update'
      end
    end
     resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
     resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
     resources :addresses, except: [:new, :show]
  
  end
    #devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

   def address_display
     '〒' + postcode + ' ' + address + ' ' + name
   end

   validates :postcode, presence:true,length: { is: 7 }
   validates :address, presence:true
   validates :name, presence:true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  belongs_to :order, optional: true

  
  def subtotal
    item.price_including_tax * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses
   has_many :orders
   has_many :cart_items, dependent: :destroy
   validates :last_name, presence:true
   validates :first_name, presence:true
   validates :kana_last_name, presence:true
   validates :kana_first_name, presence:true
   validates :phone_number, presence:true
   validates :post_code, length: { is: 7 }
   validates :address, presence:true
   validates :email, presence:true
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

 def price_including_tax
  (price * 1.1).floor  # 税率を10%として計算して切り捨て
 end

  has_one_attached :image
  
  has_many :cart_items
  belongs_to :genre, optional: true
  has_many :order_datails
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_datails
   enum payment: { credit_card: 0, transfer: 1}
   enum order_status: { waiting_for_payment: 0, payment_confirmed: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
  
    
    def total_price
    order_datails.sum{ |datail| datail.buy_price } + shipping_fee
    end
    
    def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18n.t("enums.order.order_status.#{status}"), status]
        end.to_h
    end
    
end

app/models/order_datail.rb
class OrderDatail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def self.order_detail_statuses_i18n
        order_detail_statuses.keys.map do |status|
          [I18n.t("enums.order.order_detail_status.#{status}"), status]
        end.to_h
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end
  
  def show
     @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :post_code, :address, :phone_number, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_item_path(@item), notice: '商品が更新されました'
  else
    render :edit
  end
end

private

def item_params
  params.require(:item).permit(:name, :description, :price, :is_active, :image, :genre_id)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/customers/edit.html.erb
<div class="container mt-5">
  <h2 class="mb-4"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h2>

  <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, local: true do |f| %>
    <% render "public/shared/error_messages", resource: @customer %>

     <div class="row">
          <label class="col-lg-3">名前</label>
          <div class="col-lg-3">
            <%= f.text_field :last_name,autoforcus: true, autocomplete: "last_name",  placeholder: "令和" %>
          </div>
          <div class="col-lg-3">
            <%= f.text_field :first_name,autoforcus: true, autocomplete: "first_name",  placeholder: "道子" %>
          </div>
        </div><br>

      <div class="row">
        <label class="col-lg-3">フリガナ</label>
        <div class="col-lg-3">
          <%= f.text_field :kana_last_name,autoforcus: true, autocomplete: "kana_last_name",  placeholder: "レイワ" %>
        </div>
        <div class="col-lg-3">
          <%= f.text_field :kana_first_name,autoforcus: true, autocomplete: "kana_first_name",  placeholder: "ミチコ" %>
        </div>
      </div><br>
      
       <div class="row">
        <label class="col-lg-3">郵便番号（ハイフンなし）</label>
        <div class="col-lg-3">
          <%= f.text_field :post_code,autoforcus: true, autocomplete: "post_code",  placeholder: "0000000" %>
        </div>
      </div><br>
      
      <div class="row">
        <label class="col-lg-3">住所</label>
        <div class="col-lg-3">
          <%= f.text_field :address,autoforcus: true, autocomplete: "address",  placeholder: "東京都渋谷区代々木神園町0-0" %>
        </div>
      </div><br>
      
      <div class="row">
        <label class="col-lg-3">電話番号（ハイフンなし）</label>
        <div class="col-lg-3">
          <%= f.text_field :phone_number,autoforcus: true, autocomplete: "phone_number",  placeholder: "0000000000" %>
        </div>
      </div><br>

     <div class="row">
        <label class="col-lg-3">メールアドレス</label>
        <div class="col-lg-3">
          <%= f.text_field :email,autoforcus: true, autocomplete: "email",  placeholder: "sample@exanple.com" %>
        </div>
      </div><br>

    <div class="form-group row">
  <%= f.label :is_deleted, '会員ステータス', class: 'col-sm-3 col-form-label' %>
  <div class="col-sm-9">
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_deleted, false, checked: @customer.is_deleted == false, class: 'custom-control-input', id: 'status-active' %>
      <%= f.label :is_deleted, '有効', class: 'custom-control-label', for: 'status-active' %>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_deleted, true, checked: @customer.is_deleted == true, class: 'custom-control-input', id: 'status-deleted' %>
      <%= f.label :is_deleted, '退会', class: 'custom-control-label', for: 'status-deleted' %>
    </div>
  </div>
</div>


    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-3"></div>
          <div class="col-lg-9"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h2>会員一覧</h2>

      <table class="table">
        <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
             <%= link_to "#{customer.last_name} #{customer.first_name}", admin_customer_path(customer) %>
            </td>
            <td><%= customer.email %></td>
          <td class="<%= customer.is_deleted ? 'text-gray' : 'text-green' %>"><%= customer.is_deleted ? '退会済み' : '有効' %></td>
          </tr>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div>
  <%= flash[:notice] %>
</div>  
<div class="container mt-5">
  <h2 class="mb-4 text-center"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</h2>
    <div class="row">
      <div class="col-md-6">
        <div class="pl-5">
          <p class="my-3"><strong>会員ID </strong><span style="margin-left:150px;"><%= @customer.id %></span></p>
          <p class="my-3"><strong>氏名 </strong><span style="margin-left:160px;"><%= @customer.last_name %> <%= @customer.first_name %></span></p>
          <p class="my-3"><strong>フリガナ </strong><span style="margin-left:130px;"><%= @customer.kana_last_name %> <%= @customer.kana_first_name %></span></p>
          <p class="my-3"><strong>郵便番号 </strong><span style="margin-left:130px;"><%= @customer.post_code %></span></p>
          <p class="my-3"><strong>住所 </strong><span style="margin-left:160px;"><%= @customer.address %></span></p>
          <p class="my-3"><strong>電話番号 </strong><span style="margin-left:125px;"><%= @customer.phone_number %></span></p>
          <p class="my-3"><strong>メールアドレス </strong><span style="margin-left:80px;"><%= @customer.email %></span></p>
          <p class="my-3"><strong>会員ステータス </strong><span style="margin-left:90px; color:<%= @customer.is_deleted ? 'gray' : 'green' %>;"><%= @customer.is_deleted ? '退会済み' : '有効' %></span></p>
           
          <%= link_to '編集する', edit_admin_customer_path(@customer), class: 'btn btn-success btn-space' %>
          <%= link_to '注文履歴一覧へ', admin_path, class: 'btn btn-info' %>
        </div>
      </div>
      <div class="col-md-6">
        <br>
      <%= image_tag('yurufuwa.jpg', size: "350x300") %>
      </div>
    </div>
</div>