config/routes.rb
Rails.application.routes.draw do

    #管理者側ルーティング
      devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
     namespace :admin do
  get '/' => 'homes#top' 
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update] 
  resources :orders, only: [:show, :update,] do
    member do
      patch :update_status
    end
  end
  resources :order_details, only: [:update]
end

  
  
    #顧客側ルーティング
      devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
   
    scope module: :public do
    root :to =>"homes#top" 
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check_out'
        get 'withdraw'
        patch 'withdraw_update'
      end
    end
     resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
     resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
     resources :addresses, except: [:new, :show]
  
  end
    #devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

   def address_display
     '〒' + postcode + ' ' + address + ' ' + name
   end

   validates :postcode, presence:true,length: { is: 7 }
   validates :address, presence:true
   validates :name, presence:true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  belongs_to :order, optional: true

  
  def subtotal
    item.price_including_tax * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses
   has_many :orders
   has_many :cart_items, dependent: :destroy
   validates :last_name, presence:true
   validates :first_name, presence:true
   validates :kana_last_name, presence:true
   validates :kana_first_name, presence:true
   validates :phone_number, presence:true
   validates :post_code, length: { is: 7 }
   validates :address, presence:true
   validates :email, presence:true
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

 def price_including_tax
  (price * 1.1).floor  # 税率を10%として計算して切り捨て
 end

  has_one_attached :image
  
  has_many :cart_items
  belongs_to :genre, optional: true
  has_many :order_datails
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_datails
   enum payment: { credit_card: 0, transfer: 1}
   enum order_status: { waiting_for_payment: 0, payment_confirmed: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
  
    
    def total_price
    order_datails.sum{ |datail| datail.buy_price } + shipping_fee
    end
    
    def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18n.t("enums.order.order_status.#{status}"), status]
        end.to_h
    end
    
end

app/models/order_datail.rb
class OrderDatail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def self.order_detail_statuses_i18n
        order_detail_statuses.keys.map do |status|
          [I18n.t("enums.order.order_detail_status.#{status}"), status]
        end.to_h
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_item_path(@item), notice: '商品が更新されました'
  else
    render :edit
  end
end

private

def item_params
  params.require(:item).permit(:name, :description, :price, :is_active, :image, :genre_id)
end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_datails = @order.order_datails
  end

  def update_status
    @order = Order.find(params[:id])
    if @order.update(order_params)
      @order.order_datails.update_all(production_status: "in_production") if @order.order_status == "in_production"
      @order.order_datails.update_all(production_status: "production_pending") if @order.order_status == "payment_confirmed"
      @order.order_datails.update_all(production_status: "production_not_possible") if @order.order_status == "waiting_for_payment"
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to admin_path
    else
      flash[:alert] = "注文ステータスの更新に失敗しました"
      redirect_to admins_path
    end
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(production_status: "production_pending") if @order.order_status == "payment_confirmed"
    end
    redirect_to admin_order_path(@order)
  end


  private

  def order_params
   params.require(:order).permit(:order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/orders/show.html.erb
<div class="container">
<div class="col-xs-10 col-xs-offset-1">
  <div class="row">
    <div class="col-xs-7">
    <h2>注文履歴詳細</h2><br>
     <table border="1" width="500" height="300">
      <tr>
       <th>購入者</th>
       <td>
        <%= link_to admin_customer_path(@order.customer) do %>
          <%= @order.customer.last_name %>
          <%= @order.customer.first_name %>
        <% end %>
       </td>
      </tr>
      <tr>
       <th>注文日</th>
       <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
       <th>配送先</th>
       <td>〒<%= (@order.postcode).to_s.insert(3, "-") %>&emsp;<%= @order.address %><br><%= @order.name %></td>
      </tr>
      <tr>
       <th>支払方法</th>
       <td><%= t("enums.order.payment.#{@order.payment}") %></td>
      </tr>
      <tr>
       <th>注文ステータス</th>
       <td>
        <%= form_with model: @order, url: update_status_admin_order_path(@order), method: :patch do |f| %>
          <%= f.select :order_status, Order.order_statuses_i18n, class: "form-control" %>
          <%= f.submit "更新", class: "btn btn-primary" %>
        <% end %>
       </td>
      </tr>
     </table>
    </div>
  </div>
  <div class="row">
 　  <div class="col-xs-7">
      <table border="1" width="600" height="150">
       <tr>
         <th>商品名</th>
         <th>単価（税込）</th>
         <th>数量</th>
         <th>小計</th>
         <th>製作ステータス</th>
       </tr>
       <% @order_datails.each do |order_datail| %>
       <tr>
         <td><%= order_datail.item.name %></td>
         <td>￥<%= order_datail.item.price_including_tax %></td>
         <td><%= order_datail.quantity %></td>
         <td>￥<%= order_datail.item.price_including_tax * order_datail.quantity %></td>
         <td>
          <%= form_with model:order_datail, url: admin_order_detail_path(order_datail), local: true do |f| %>
              <%= f.select :production_status, [["製作不可", "production_not_possible"], ["製作待ち", "production_pending"], ["製作中", "in_production"], ["製作完了", "production_complete"]] %>
              <%= f.submit "更新", class: 'btn btn-primary' %>
            <% end %>
         </td>
       </tr>
       <% end %>
   　  </table>
    </div>
    <div class="col-md-3">
      <table class="table">
        <tr>
          <td>商品合計</td>
          <td>￥<%= @order_datails.sum{ |datail| datail.buy_price }.to_i %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td>￥<% @shipping_fee = 800 %><%= @shipping_fee.to_i %></td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td>￥<%= @order.total_price.to_i %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
</div>