config/routes.rb
Rails.application.routes.draw do

    #管理者側ルーティング
      devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
     namespace :admin do
  get '/' => 'homes#top' 
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update] 
  resources :orders, only: [:show, :update,] do
    member do
      patch :update_status
    end
  end
  resources :order_details, only: [:update]
end

  
  
    #顧客側ルーティング
      devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
   
    scope module: :public do
    root :to =>"homes#top" 
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check_out'
        get 'withdraw'
        patch 'withdraw_update'
      end
    end
     resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
     resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
     resources :addresses, except: [:new, :show]
  
  end
    #devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

   def address_display
     '〒' + postcode + ' ' + address + ' ' + name
   end

   validates :postcode, presence:true,length: { is: 7 }
   validates :address, presence:true
   validates :name, presence:true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  belongs_to :order, optional: true

  
  def subtotal
    item.price_including_tax * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses
   has_many :orders
   has_many :cart_items, dependent: :destroy
   validates :last_name, presence:true
   validates :first_name, presence:true
   validates :kana_last_name, presence:true
   validates :kana_first_name, presence:true
   validates :phone_number, presence:true
   validates :post_code, length: { is: 7 }
   validates :address, presence:true
   validates :email, presence:true
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

 def price_including_tax
  (price * 1.1).floor  # 税率を10%として計算して切り捨て
 end

  has_one_attached :image
  
  has_many :cart_items
  belongs_to :genre, optional: true
  has_many :order_datails
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_datails
   enum payment: { credit_card: 0, transfer: 1}
   enum order_status: { waiting_for_payment: 0, payment_confirmed: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
  
    
    def total_price
    order_datails.sum{ |datail| datail.buy_price } + shipping_fee
    end
    
    def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18n.t("enums.order.order_status.#{status}"), status]
        end.to_h
    end
    
end

app/models/order_datail.rb
class OrderDatail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def self.order_detail_statuses_i18n
        order_detail_statuses.keys.map do |status|
          [I18n.t("enums.order.order_detail_status.#{status}"), status]
        end.to_h
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :set_genre, only: [:edit, :update]
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを登録しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを更新しました"
    else
      render :edit
    end
  end

  private
  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_item_path(@item), notice: '商品が更新されました'
  else
    render :edit
  end
end

private

def item_params
  params.require(:item).permit(:name, :description, :price, :is_active, :image, :genre_id)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/genres/edit.html.erb
<h1 class="text-center">ジャンル編集</h1>

<div class="row justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: @genre, url: admin_genre_path(@genre), method: :patch, class: 'form-group') do |f| %>
      <%= f.label :name, "ジャンル名", class: 'form-label' %>
      <div class="input-group mb-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'ジャンル名を入力してください' %>
        <div class="input-group-append">
          <%= f.submit "更新", class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<h1 class="text-center">ジャンル一覧・追加</h1>

<div class="row justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: @genre, url: admin_genres_path, class: 'form-group') do |f| %>
      <%= f.label :name, "ジャンル名", class: 'form-label' %>
      <div class="input-group mb-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'ジャンル名を入力してください' %>
        <div class="input-group-append">
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-8">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ジャンル名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<h3 class="text-center">商品編集</h3>
<%= form_with model: [:admin, @item], local: true, class: 'col-6 mx-auto' do |f| %>
  <div class="form-group row">
    <%= f.label :image, '商品画像', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, '商品名', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, placeholder: "商品名", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, '商品説明', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, placeholder: "商品説明", class: 'form-control' %>
    </div>
  </div>
   <div class="form-group row">
    <%= f.label :genre_id, 'ジャンル', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {}, {class: 'form-control'} %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :price, '税抜価格', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9 input-group">
      <%= f.number_field :price, placeholder: "1000", class: 'form-control' %>
      <div class="input-group-append">
        <span class="input-group-text">円</span>
      </div>
    </div>
  </div>
  
 <div class="form-group row">
  <%= f.label :is_active, '販売ステータス', class: 'col-sm-3 col-form-label' %>
  <div class="col-sm-9">
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_active, true, checked: @item.is_active, class: 'custom-control-input', id: 'is_active-true' %>
      <%= f.label :is_active, '販売中', class: 'custom-control-label', for: 'is_active-true' %>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_active, false, checked: !@item.is_active, class: 'custom-control-input', id: 'is_active-false' %>
      <%= f.label :is_active, '販売停止中', class: 'custom-control-label', for: 'is_active-false' %>
    </div>
  </div>
</div>


  </div>
  <div class="form-group row">
    <div class="col-sm-9 offset-sm-3">
      <%= f.submit '変更を保存', class: 'btn btn-success text-white' %>
    </div>
  </div>
<% end %>

app/views/admin/items/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <h2>商品一覧</h2>
    <div class="ml-auto">
      <%= link_to '商品新規登録', new_admin_item_path, class: 'btn', style: 'background-color: #E4FF8D;' %>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
           <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item) %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td style="margin-left:90px; color:green;">
            <%= item.is_active ? '販売中' : '販売停止中' %></td>
            </td>
           </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<h3 class="text-center">商品新規登録</h3>
<%= form_with model: [:admin, @item], local: true, class: 'col-6 mx-auto' do |f| %>
  <div class="form-group row">
    <%= f.label :image, '商品画像', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, '商品名', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, placeholder: "商品名", placeholder: "商品名", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, '商品説明', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, placeholder: "商品説明", placeholder: "商品説明", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :price, '税抜価格', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9 input-group">
      <%= f.number_field :price, placeholder: "1000", placeholder: "1000", class: 'form-control' %>
      <div class="input-group-append">
        <span class="input-group-text">円</span>
      </div>
    </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :genre_id, 'ジャンル', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {}, {class: 'form-control'} %>
    </div>
  </div>
  
  <div class="form-group row">
  <%= f.label :is_active, '販売ステータス', class: 'col-sm-3 col-form-label' %>
  <div class="col-sm-9">
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_active, true, checked: @item.is_active, class: 'custom-control-input', id: 'is_active-true' %>
      <%= f.label :is_active, '販売中', class: 'custom-control-label', for: 'is_active-true' %>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
      <%= f.radio_button :is_active, false, checked: !@item.is_active, class: 'custom-control-input', id: 'is_active-false' %>
      <%= f.label :is_active, '販売停止中', class: 'custom-control-label', for: 'is_active-false' %>
    </div>
  </div>
</div>

  </div>
  <div class="form-group row">
    <div class="col-sm-9 offset-sm-3">
      <%= f.submit '新規投稿', class: 'btn btn-success text-white' %>
    </div>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <h2 class="text-center my-5">商品詳細</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div style="padding-left:20%;">
        <%= image_tag url_for(@item.image), class: 'img-fluid', style: 'width: 65%;' %>
      </div>
    </div>
    <div class="col-md-6">
      <p class="my-4"><strong>商品名 </strong><span style="margin-left:150px;"><%= @item.name %></span></p>
      <p class="my-4"><strong>商品説明 </strong><span style="margin-left:135px;"><%= @item.description %></span></p>
      <p class="my-4"><strong>税込価格（税抜価格） </strong><span style="margin-left:40px;"><%= number_with_delimiter((@item.price * 1.1).round) %>円 ( <%= number_with_delimiter(@item.price) %>円 )</span></p>
      <p class="my-4"><strong>ジャンル </strong><span style="margin-left:145px;"><%= @item.genre ? @item.genre.name : "ジャンル未設定" %></span></p>
     <p><strong>販売ステータス:</strong><span style="margin-left:90px; color:green;"><%= @item.is_active ? '販売中' : '販売停止中' %></span></p>
      <%= link_to '編集する', edit_admin_item_path(@item), class: 'btn btn-success' %>
    </div>
  </div>
</div>