config/routes.rb
Rails.application.routes.draw do

    #管理者側ルーティング
      devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
     namespace :admin do
  get '/' => 'homes#top' 
  resources :items, except: [:destroy]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update] 
  resources :orders, only: [:show, :update,] do
    member do
      patch :update_status
    end
  end
  resources :order_details, only: [:update]
end

  
  
    #顧客側ルーティング
      devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
   
    scope module: :public do
    root :to =>"homes#top" 
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check_out'
        get 'withdraw'
        patch 'withdraw_update'
      end
    end
     resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
     resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
     resources :addresses, except: [:new, :show]
  
  end
    #devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

   def address_display
     '〒' + postcode + ' ' + address + ' ' + name
   end

   validates :postcode, presence:true,length: { is: 7 }
   validates :address, presence:true
   validates :name, presence:true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  belongs_to :order, optional: true

  
  def subtotal
    item.price_including_tax * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses
   has_many :orders
   has_many :cart_items, dependent: :destroy
   validates :last_name, presence:true
   validates :first_name, presence:true
   validates :kana_last_name, presence:true
   validates :kana_first_name, presence:true
   validates :phone_number, presence:true
   validates :post_code, length: { is: 7 }
   validates :address, presence:true
   validates :email, presence:true
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

 def price_including_tax
  (price * 1.1).floor  # 税率を10%として計算して切り捨て
 end

  has_one_attached :image
  
  has_many :cart_items
  belongs_to :genre, optional: true
  has_many :order_datails
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_datails
   enum payment: { credit_card: 0, transfer: 1}
   enum order_status: { waiting_for_payment: 0, payment_confirmed: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
  
    
    def total_price
    order_datails.sum{ |datail| datail.buy_price } + shipping_fee
    end
    
    def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18n.t("enums.order.order_status.#{status}"), status]
        end.to_h
    end
    
end

app/models/order_datail.rb
class OrderDatail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def self.order_detail_statuses_i18n
        order_detail_statuses.keys.map do |status|
          [I18n.t("enums.order.order_detail_status.#{status}"), status]
        end.to_h
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cakeshop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6781c6f16f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&display=swap" rel="stylesheet">
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark ">
        <div class="container">
          <a class="navbar-brand p-3" href="<%= customer_session_path %>">
           <%= image_tag('nagano (2).png', size: "130x100") %>
          </a>
          <ul class="navbar-nav ml-auto ">
            <% if admin_signed_in? %>
              <%# if request.fullpath.include? "/admin" %>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                    <%= link_to "商品一覧", admin_items_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-hot" style="color: white;" ></i>
                    <%= link_to "会員一覧", admin_customers_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                    <%= link_to "注文履歴一覧", admin_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-hot" style="color: white;" ></i>
                    <%= link_to "ジャンル一覧", admin_genres_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-right-from-bracket" style="color: white;" ></i>
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                  </div>
                </li>
              <%# else %>
              <%# end %>
            <% elsif customer_signed_in? %>
                <li style="width:300px; margin:0 auto;">
                  ようこそ、<%= current_customer.last_name %>さん！
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                   <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                   <%= link_to "マイページ", customer_path(current_customer) %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-hot" style="color: white;" ></i>
                    <%= link_to "商品一覧", items_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                    <%= link_to "カート", cart_items_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-right-from-bracket" style="color: white;" ></i>
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                    <%= link_to "About", about_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-hot" style="color: white;" ></i>
                    <%= link_to "商品一覧", items_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-mug-saucer" style="color: white;" ></i>
                    <%= link_to "新規登録", new_customer_registration_path %>
                  </div>
                </li>
                <li class="nav-item">
                  <div type="button" class="btn btn-outline-primary btn-custom">
                    <i class="fa-solid fa-right-to-bracket" style="color: white;" ></i>
                    <%= link_to "ログイン", new_customer_session_path %>
                  </div>
                </li>
            <% end %>
          </ul>
        </div>
      </nav>
     <hr class="decorative-line">
      <%= form_with(url: items_path, method: :get, local: true, html: { class: "form-inline" }) do |f| %>
     <div class="form-group mx-sm-3 mb-2">
      <%= f.label :search, "商品検索", class: "sr-only" %>
      <%= f.text_field :search, class: "form-control", placeholder: "item&ジャンルをけんさく" %>
     </div>
      <%= f.submit "検索", class: "btn btn-pink mb-2" %>
      <% end %>

    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
    <hr class="decorative-line">
    </footer>
  </body>
</html>